server:
  port: 8088
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2HYhy/config-server/
          search-paths: config-server
          username:
          password:

# 服务端从git获取配置信息，客户端在应用启动时从服务端获取配置信息
# 启动后可访问：
# http://localhost:8088/config/dev
# http://localhost:8088/config/test/master
# http://localhost:8088/config-dev.yml
# http://localhost:8088/config-pro.properties

# http://localhost:8088/{application}/{profile}/[{label}]
# http://localhost:8088/{application}-{profile}.yml
# http://localhost:8088/{label}/{application}-{profile}.yml

