server:
  port: 8081

spring:
  application:
    name: config  # 和配置文件名保持一致
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2HYhy/springcloud
          searchPaths: configdemo