server:
  port: 8080
  context-path: /hyh
spring:
  application:
    name:  spring-boot-admin
  boot:
    admin:
      context-path: /admin
      url: http://localhost:${server.port}/${server.context-path}
  jackson:
    serialization: true
endpoints:
  sensitive: false   # 不用权限校验

# http://localhost:8080/hyh/admin 出现可视化界面



eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10

# eureka-cient添加eureka后，访问admin-server时，server，admin，eureka三者都会在监控列表中，eureka实例被监控的前提是允许本身被当做注册