spring:
# Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
# 服务路由配置
zuul:
  routes:
    local:
      path: /user-demo/**
      url: http://localhost:8090/user-demo/
# 服务限流配置
  ratelimit:
    enabled: true
    policies:
      local:
        limit: 3  # 70秒内发送多个请求，前3个返回200正常响应，后面的返回429太多请求
        refreshInterval: 70
        type:
          - ORIGIN
          - URL
          - USER
  strip-prefix: true
