server:
  port: 8084
spring:
  application:
    name: spring-cloud-gateway-ratelimit
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://httpbin.org:80/get
        predicates:
        - Method=GET
        filters:
        - name: RequestRateLimiter  # 即内置的RequestRateLimiterGatewayFilterFactory
          args:
#            key-resolver: '#{@hostKeyResolver}'   # 获取对应的bean对象
#            key-resolver: '#{@urlKeyResolver}'
            key-resolver: '#{@userKeyResolver}'
            redis-rate-limiter.replenishRate: 1   # 每秒平均速率
            redis-rate-limiter.burstCapacity: 2   # 令牌桶总容量
  redis:
    host: localhost
    port: 6379
    database: 0


